package view;

import java.sql.*;
import DAO.ModuloConexao;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class ViewUsuario extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public ViewUsuario() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    private void consultar() {
        String sql = "SELECT * FROM tbl_usuario WHERE pk_usu_id=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, jtfId.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                jtfNome.setText(rs.getString(2));
                jtfFone.setText(rs.getString(3));
                jtfLogin.setText(rs.getString(4));
                jpfSenha.setText(rs.getString(5));
                jcbPerfil.setSelectedItem(rs.getString(6));
            } else {
                limpar_tela();
                JOptionPane.showMessageDialog(null, "Usuário não cadastrado!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void adicionar() {
        String sql = "INSERT INTO tbl_usuario (usu_nome, usu_fone, usu_login, usu_senha, usu_perfil) VALUES (?,?,?,?,?);";
        try {
            pst = conexao.prepareStatement(sql);
            if (jtfNome.getText() == null || jtfFone.getText() == null || jtfLogin.getText() == null || jpfSenha.getText() == null || jcbPerfil.getSelectedItem().toString() == "<Selecione o Perfil>") {
                JOptionPane.showMessageDialog(null, "Todos os campos precisam ser preenchidos.");
            } else {
                pst.setString(1, jtfNome.getText());
                pst.setString(2, jtfFone.getText());
                pst.setString(3, jtfLogin.getText());
                pst.setString(4, jpfSenha.getText());
                pst.setString(5, jcbPerfil.getSelectedItem().toString());
                // Fazer o commit no SQL usando o executeUpdate().
                pst.executeUpdate();
                limpar_tela();
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void limpar_tela() {
        jtfId.setText(null);
        jtfNome.setText("");
        jtfFone.setText("");
        jtfLogin.setText("");
        jpfSenha.setText("");
        jcbPerfil.setSelectedItem("<Selecione o Perfil>");
    }

    private void alterar() {
        String sql = "UPDATE tbl_usuario SET usu_nome=?, usu_fone=?, usu_login=?, usu_senha=?, usu_perfil=? WHERE pk_usu_id=?";
        try {
            if (jtfNome.getText() == null || jtfFone.getText() == null || jtfLogin.getText() == null || jpfSenha.getText() == null || jcbPerfil.getSelectedItem().toString() == "<Selecione o Perfil>") {
                JOptionPane.showMessageDialog(null, "Todos os campos precisam ser preenchidos.");
            } else {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, jtfNome.getText());
                pst.setString(2, jtfFone.getText());
                pst.setString(3, jtfLogin.getText());
                pst.setString(4, jpfSenha.getText());
                pst.setString(5, jcbPerfil.getSelectedItem().toString());
                pst.setString(6, jtfId.getText());
                limpar_tela();
                pst.executeUpdate(); // Commit do BD
                JOptionPane.showMessageDialog(null, "Alterado com sucesso.");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void remover(){
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover esse usuário?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION){
            String sql = "DELETE FROM tbl_usuario WHERE pk_usu_id=?";
            try{
                pst = conexao.prepareStatement(sql);
                pst.setString(1, jtfId.getText());
                pst.executeUpdate();
                limpar_tela();
                JOptionPane.showMessageDialog(null, "Usuário removido com sucesso.");
            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbPerfil = new javax.swing.JComboBox<>();
        jtfId = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfFone = new javax.swing.JTextField();
        jtfLogin = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jbDelete = new javax.swing.JButton();
        jbAdd = new javax.swing.JButton();
        jbSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuários");
        setMaximumSize(new java.awt.Dimension(745, 479));
        setMinimumSize(new java.awt.Dimension(745, 479));
        setPreferredSize(new java.awt.Dimension(745, 479));

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel1.setText("*ID");

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setText("*Nome");

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel3.setText("*Telefone");

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel4.setText("*Login");

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel5.setText("*Senha");

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel6.setText("*Perfil");

        jcbPerfil.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jcbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione o Perfil>", "admin", "user" }));

        jtfId.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtfId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfIdKeyPressed(evt);
            }
        });

        jtfNome.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jtfFone.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jtfLogin.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jpfSenha.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PNG/remove-user-icon64.png"))); // NOI18N
        jbDelete.setToolTipText("Deletar Usuário");
        jbDelete.setBorderPainted(false);
        jbDelete.setContentAreaFilled(false);
        jbDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });

        jbAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PNG/add-user-icon64.png"))); // NOI18N
        jbAdd.setToolTipText("Salvar / Adicionar");
        jbAdd.setBorderPainted(false);
        jbAdd.setContentAreaFilled(false);
        jbAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jbSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PNG/save64.png"))); // NOI18N
        jbSave.setToolTipText("Salvar");
        jbSave.setBorderPainted(false);
        jbSave.setContentAreaFilled(false);
        jbSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jLabel7.setText("<--- Insira o ID e precione ENTER para buscar");

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("* Campos obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbDelete)
                                    .addGap(38, 38, 38)
                                    .addComponent(jbSave)
                                    .addGap(35, 35, 35)
                                    .addComponent(jbAdd))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtfNome)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAdd)
                    .addComponent(jbDelete)
                    .addComponent(jbSave))
                .addGap(82, 82, 82))
        );

        setBounds(0, 0, 745, 479);
    }// </editor-fold>//GEN-END:initComponents

    //Método para apertar o ENTER e consultar
    private void jtfIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jtfId == null) {
                limpar_tela();
            } else {
                consultar();
            }

        }

    }//GEN-LAST:event_jtfIdKeyPressed

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        adicionar();
    }//GEN-LAST:event_jbAddActionPerformed

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        alterar();
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        remover();
    }//GEN-LAST:event_jbDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbSave;
    private javax.swing.JComboBox<String> jcbPerfil;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfFone;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
